### ISSUE TITLE
useEffect console warning about

### ISSUE THREAD

**Issue by kostyambaaa** [rafaelquintanilha/use-clock#1]
In console I receive a warning with text bellow:
`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.`

Can you fix it please?

**Comment by rafaelquintanilha** [comment]
@kostyambaaa it should be fixed in the last version.
